# Generated by Django 3.1.4 on 2020-12-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': False},
        ),
    ]
