# Generated by Django 3.1.4 on 2020-12-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20201209_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': True},
        ),
    ]
