# Generated by Django 3.1.4 on 2020-12-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20201209_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
