# Generated by Django 3.1.4 on 2020-12-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_remove_contact_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': False},
        ),
    ]
